### ISSUE TITLE
Notebook in text format

### ISSUE THREAD

**Issue by vinertia** [justmarkham/pandas-videos#1]
Hi,

I just created my account in Github, pardon the simple question.

Is it possible to download the notebooks that you have provided in text format?

Here's the link of the one I'm looking at:
http://nbviewer.jupyter.org/github/justmarkham/pandas-videos/blob/master/pandas.ipynb#25.-How-do-I-work-with-dates-and-times-in-pandas%3F-%28video%29

I'm planning to work with the notebooks without having to type the code one by one.
If it's possible to do this please teach me how! Thank you!

**Comment by justmarkham** [comment]
I think this is what you are looking for: https://nbconvert.readthedocs.io/en/latest/

Hope that helps!
