### ISSUE TITLE
How to add a new time column with new calculated time data?

### ISSUE THREAD

**Issue by mrbiggleswirth** [justmarkham/pandas-videos#3]
Hi Just Markham,

I want to add +8 hours to all the existing times and save it to a new column in the DataFrame. I only figured out how to create a new column. But I don't know how to add my delta time to the new time data.

Electronically yours,
Mr. Biggles

```
from datetime import timedelta
import pandas as pd

ufo = pd.read_csv('http://bit.ly/uforeports')

print("")
ufo['Time'] = pd.to_datetime(ufo.Time)
print(ufo)

print("")
print("_______________________________________________________________________")
print("")

print("ufo.dtypes")
print(ufo.dtypes)

print("")
print("_______________________________________________________________________")
print("")

# Add a new column with new data.

delta = timedelta(hours=-8)
# calc_utc_time = data_cell + delta

ufo['utc_time'] = ufo.Time
print(ufo)

print("")
print("_______________________________________________________________________")
print("")

print("ufo.dtypes")
print(ufo.dtypes)

print("")
print("_______________________________________________________________________")
print("")
```

**Comment by mrbiggleswirth** [comment]
I solved it! :) The required Kung Fu can be found in these lessons:

**Lesson: 25** [How do I work with dates and times in pandas?](https://www.youtube.com/watch?v=yCgJGsg0Xa4&list=PL5-da3qGB5ICCsgW1MxlZ0Hq8LL5U3u9y&index=25) (10:20)

**Lesson: 8** [How do I filter rows of a pandas DataFrame by column value?](https://www.youtube.com/watch?v=2AFGPdNn4FM&list=PL5-da3qGB5ICCsgW1MxlZ0Hq8LL5U3u9y&index=8) (13:44)

Thank you, Shifu Markham!

**Comment by justmarkham** [comment]
@mrbiggleswirth Great to hear it! 🙌
