### ISSUE TITLE
Drop duplicates from multiple columns

### ISSUE THREAD

**Issue by Nasidiqi** [justmarkham/pandas-videos#6]
How do I find and remove duplicate rows in multiple columns in pandas?

df.col_1.drop_duplicates()

I have 5 columns how can I do that?

**Comment by Baniodeh** [comment]
columns_to_drop = []

and then drop the columns_to_drop_list
    Am Donnerstag, 30. Juli 2020, 02:25:24 MESZ hat Nasidiqi <notifications@github.com> Folgendes geschrieben:  
 
 


How do I find and remove duplicate rows in multiple columns in pandas?

df.col_1.drop_duplicates()

I have 5 columns how can I do that?
