### ISSUE TITLE
Converting pandas.Timestamp into date only by removing timestamp

### ISSUE THREAD

**Issue by shksajawal** [justmarkham/pandas-videos#7]
You've made a good video but you missed this one thing to explain. Actually the situation is in below code.

```
class NumpyEncoder(DjangoJSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, pd.Timestamp):
            return str(obj)

    return super().default(obj)
```

    with pd.ExcelFile(default_storage.open(path)) as xls:
        sheet_names = xls.sheet_names
        sheets_df = [pd.read_excel(xls, sheet_name, header=None)
                     for sheet_name in sheet_names]
        worksheets_columns = [list(sheet_df.columns) for sheet_df in sheets_df]
        worksheets_data = [json.loads(json.dumps(
            sheet_df.fillna('').applymap(str).to_numpy(), cls=NumpyEncoder))
                           for sheet_df in sheets_df]

I need to convert pandas.Timestamp in the situation above to date only. Currently shows timestamp also. 

Thanks in advance.

**Comment by justmarkham** [comment]
Sorry, I won't be able to assist you... good luck!
